# netlify.toml

[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200